[package]
name = "hulk-compiler"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hulk"
path = "src/main.rs"

[[bin]]
name = "hulk-playground"
path = "src/bin/playground.rs"

[dependencies]
actix-web = "4"
actix-files = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
